version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    network_mode: "host"
    environment:
      # Se actualiza la URI para que, al usar host networking, MongoDB se encuentre en localhost.
      - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/CYCLOPS
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    network_mode: "host"
    # Al estar en modo host no se requiere mapear puertos.
    volumes:
      - ./mosquitto/config:/mosquitto/broker
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mongo_data:
